local toolbox = require('toolbox')
vim.cmd([[command! -nargs=1 CdoMacro lua toolbox.CdoMacro(<f-args>)]])
vim.cmd([[command! -nargs=1 CfdoMacro lua toolbox.CfdoMacro(<f-args>)]])
vim.cmd([[command! -range -nargs=1 MultiLineMacro lua toolbox.MultiLineMacro(<f-args>)]])
vim.cmd([[command! CopyFilename lua toolbox.CopyFilename()]])
